name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # Weekly scan
    - cron: "20 4 * * 1"

jobs:
  tests:
    runs-on: [self-hosted, amd64, tiobe, noble]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Determine TiCS run conditions
        id: tics-condition
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "tics_mode=client" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]] || [[ "${{ github.event_name }}" == "schedule" ]]; then
            echo "tics_mode=qserver" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        run: |
          uv tool install --python-preference only-managed tox --with tox-uv
          uv sync --locked --all-extras --dev # Needed for TiCS

      - name: Install dependencies (QServer)
        if: steps.tics-condition.outputs.tics_mode == 'qserver'
        run: |
          set -e
          uv add --frozen flake8 Pylint

      - name: Run tests
        run: |
          tox
          mkdir coverage
          mv coverage.xml ./coverage/

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tests-${{ github.job }}-artifacts-${{ github.run_attempt }}
          path: ./coverage

      - name: Upload to codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: "TiCS"
        if: ${{ steps.tics-condition.outputs.tics_mode != '' }}
        uses: tiobe/tics-github-action@v3
        with:
          mode: ${{ steps.tics-condition.outputs.tics_mode }}
          project: ubuntu-insights-k8s-operator
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
